#!/usr/bin/env python
# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
"""Run beam search with a recipe config and save per-(beam, step) trace.

The trace itself is a vllm-method experiment (gemm_opt=false, chunk_size=none),
so this script also writes a `beam_search_request_timings_vllm_n{n}.csv` in
the same format as the FD/ours runs produced by `scripts/beam_search_beam.py`.

Usage:
    python scripts/beam_search_task_trace.py recipes/beam-search.yaml

Outputs (under data/{model_path}/{dataset_short_name}/):
    beam_search_n{n}                            Python literal with REQUEST_STEP_GEN_TOKENS
                                                = {(problem_idx, step_idx, beam_idx): tokens}
    beam_search_n{n}.csv                        CSV: problem, step_idx, beam_idx, gen_len
    beam_search_n{n}_timing.csv                 CSV: problem, step_idx, beam_idx, gen_time_ms
    beam_search_request_timings_vllm_n{n}.csv   CSV: problem, beam, token_length, gen_time_ms
                                                (cumulative per-beam, matches FD/ours format)
"""

import csv
import logging
import os
from pathlib import Path

# Reuse the search core from scripts/beam_search_beam.py. When invoked as
# `python scripts/beam_search_task_trace.py ...` the scripts/ directory is on
# sys.path automatically, so this import resolves without any setup.
import beam_search_beam
import torch
from beam_search_beam import (
    _maybe_load_attn_lut,
    _run_one_problem,
    _short_problem,
    _warmup_attn_kernels,
)
from vllm import LLM

from sal.config import Config
from sal.utils.data import get_dataset
from sal.utils.parser import H4ArgumentParser

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def _write_trace(trace, completed, path):
    """Python literal with two structures consumed by beam_search_beam:
        REQUEST_STEP_GEN_TOKENS = {(problem_idx, step_idx, beam_idx): gen_len}
        REQUEST_STEP_COMPLETED  = {(problem_idx, step_idx, beam_idx), ...}
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/beam_search_task_trace.py.",
        "# Forced per-step gen lengths and per-step completion flags.",
        "REQUEST_STEP_GEN_TOKENS = {",
    ]
    for key in sorted(trace.keys()):
        lines.append(f"    {key}: {trace[key]},")
    lines.append("}")
    lines.append("")
    lines.append("REQUEST_STEP_COMPLETED = {")
    for key in sorted(completed):
        lines.append(f"    {key},")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines))


def _write_trace_csv(trace, path, problem_short_by_idx):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["problem", "step_idx", "beam_idx", "gen_len"])
        for key in sorted(trace.keys()):
            problem_idx, step_idx, beam_idx = key
            writer.writerow([
                problem_short_by_idx[problem_idx],
                step_idx, beam_idx, trace[key],
            ])


def _write_timing_csv(timings, path, problem_short_by_idx):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["problem", "step_idx", "beam_idx", "gen_time_ms"])
        for key in sorted(timings.keys()):
            problem_idx, step_idx, beam_idx = key
            writer.writerow([
                problem_short_by_idx[problem_idx],
                step_idx, beam_idx, timings[key],
            ])


def _write_request_timings_csv(records, path):
    """Per-(problem, beam) cumulative timing — same schema as
    `beam_search_request_timings_<method>_n{n}.csv` produced by
    scripts/beam_search_beam.py.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["problem", "beam", "token_length", "gen_time_ms"])
        for problem_short, completed in records:
            for beam_idx, beam in enumerate(completed):
                writer.writerow([
                    problem_short, beam_idx,
                    beam.completion_tokens, beam.gen_time_ms,
                ])


def main():
    parser = H4ArgumentParser(Config)
    config = parser.parse()

    if config.approach != "beam_search":
        raise ValueError(
            f"beam_search_task_trace only supports approach=beam_search, got {config.approach}"
        )

    # Trace runs always use vanilla settings (matches best_of_n_task_trace).
    config.gemm_opt = False
    config.chunk_size = "none"

    # Disable forced per-step lengths *and* completion replay so the engine
    # generates naturally and we capture the resulting token counts as the
    # trace. Without this, a pre-existing trace file (from a prior run)
    # would replay through _run_one_problem and we'd record the replay, not
    # fresh data.
    beam_search_beam.REQUEST_STEP_GEN_TOKENS = {}
    beam_search_beam.REQUEST_STEP_COMPLETED = set()

    os.environ["VLLM_TRITON_DECODE_KERNEL"] = config.triton_decode_kernel

    num_gpus = torch.cuda.device_count()
    llm = LLM(
        model=config.model_path,
        gpu_memory_utilization=config.gpu_memory_utilization,
        enable_prefix_caching=True,
        seed=config.seed,
        tensor_parallel_size=num_gpus,
        load_format="safetensors",
        task="generate",
        dtype="auto",
        disable_cascade_attn=True,
    )

    logger.info("Warming up FA and FD-path Triton kernels...")
    _warmup_attn_kernels(llm)
    logger.info("Warmup done.")

    attn_lut = _maybe_load_attn_lut(config)  # None when chunk_size == "none"

    dataset = get_dataset(config)

    output_dir = Path(config.output_dir or f"data/{config.model_path}")
    dataset_short = config.dataset_name.split("/")[-1]
    out_dir = output_dir / dataset_short
    out_dir.mkdir(parents=True, exist_ok=True)

    trace_path             = out_dir / f"beam_search_n{config.n}"
    trace_csv_path         = out_dir / f"beam_search_n{config.n}.csv"
    timing_csv_path        = out_dir / f"beam_search_n{config.n}_timing.csv"
    # The trace IS a vllm-method experiment, so emit the cumulative
    # per-beam CSV in the same schema as scripts/beam_search_beam.py.
    vllm_request_timings_path = (
        out_dir / f"beam_search_request_timings_vllm_n{config.n}.csv"
    )

    trace: dict[tuple[int, int, int], int] = {}
    timings: dict[tuple[int, int, int], float] = {}
    completed_set: set[tuple[int, int, int]] = set()
    problem_short_by_idx: dict[int, str] = {}
    request_records: list[tuple[str, list]] = []

    for problem_idx, ex in enumerate(dataset):
        problem = ex["problem"]
        problem_short = _short_problem(problem_idx, problem)
        problem_short_by_idx[problem_idx] = problem_short

        completed, step_trace = _run_one_problem(
            problem, problem_idx, config, llm, attn_lut)
        for iter_idx, slot_idx, gen_len, gen_time_ms, was_completed in step_trace:
            key = (problem_idx, iter_idx, slot_idx)
            trace[key] = int(gen_len)
            timings[key] = float(gen_time_ms)
            if was_completed:
                completed_set.add(key)
        request_records.append((problem_short, completed))
        max_step = max((s for _, s, _, _, _ in step_trace), default=-1)
        logger.info(
            "[%d/%d] %d entries, last_step=%d",
            problem_idx + 1, len(dataset), len(step_trace), max_step,
        )

    _write_trace(trace, completed_set, trace_path)
    _write_trace_csv(trace, trace_csv_path, problem_short_by_idx)
    _write_timing_csv(timings, timing_csv_path, problem_short_by_idx)
    _write_request_timings_csv(request_records, vllm_request_timings_path)
    logger.info(
        "Saved %d trace entries (%d completed); outputs: %s, %s, %s, %s",
        len(trace), len(completed_set),
        trace_path, trace_csv_path, timing_csv_path,
        vllm_request_timings_path,
    )


if __name__ == "__main__":
    main()
