#!/usr/bin/env python
# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
"""Run best-of-n with a recipe config and save a per-beam token-length trace.

Usage:
    python scripts/best_of_n_task_trace.py recipes/best-of-n.yaml

The script runs the best-of-n approach end-to-end (without forced beam
lengths), then writes (problem_idx, beam_idx) -> generated_token_length to a
Python literal file. The companion module `sal.search.best_of_n_beam` loads
this file at import time into REQUEST_GEN_TOKENS so subsequent runs can
reproduce the exact per-beam generation lengths.
"""

import csv
import logging
import os
from pathlib import Path

import torch
from vllm import LLM, SamplingParams
from vllm.attention.ops import chunked_prefill_paged_decode as cpd

from sal.config import Config
from sal.models.reward_models import load_prm
from sal.search import best_of_n_beam
from sal.search import best_of_n_beam as best_of_n_beam_module
from sal.utils.data import get_dataset, save_dataset
from sal.utils.parser import H4ArgumentParser
from sal.utils.score import score

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def _warmup_attn_kernels(llm):
    """JIT-compile both FA and FD-path Triton kernels before measurement.

    Mirrors the warmup in scripts/test_time_compute.py so PRM memory accounting
    is consistent between the two entry points.
    """
    sp = SamplingParams(temperature=0.0, max_tokens=20, min_tokens=20)
    prev = cpd.PROFILE_CHUNK_SIZE_PAGE
    try:
        cpd.PROFILE_CHUNK_SIZE_PAGE = None
        llm.generate(["warmup"], sp, use_tqdm=False)
        cpd.PROFILE_CHUNK_SIZE_PAGE = 4
        llm.generate(["warmup"], sp, use_tqdm=False)
    finally:
        cpd.PROFILE_CHUNK_SIZE_PAGE = prev


def _write_trace(trace, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/best_of_n_task_trace.py.",
        "# (problem_idx, beam_idx) -> generated token length.",
        "REQUEST_GEN_TOKENS = {",
    ]
    for problem_idx, beam_idx in sorted(trace.keys()):
        lines.append(
            f"    ({problem_idx}, {beam_idx}): {trace[(problem_idx, beam_idx)]},"
        )
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines))


def _write_trace_csv(trace, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["problem_idx", "beam_idx", "gen_len"])
        for problem_idx, beam_idx in sorted(trace.keys()):
            writer.writerow(
                [problem_idx, beam_idx, trace[(problem_idx, beam_idx)]]
            )


def _write_timing_csv(timings, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["problem_idx", "beam_idx", "gen_time_ms"])
        for problem_idx, beam_idx in sorted(timings.keys()):
            writer.writerow(
                [problem_idx, beam_idx, timings[(problem_idx, beam_idx)]]
            )


def main():
    parser = H4ArgumentParser(Config)
    config = parser.parse()

    if config.approach != "best_of_n":
        raise ValueError(
            f"best_of_n_task_trace only supports approach=best_of_n, got {config.approach}"
        )

    # Trace runs ignore these regardless of what the recipe sets.
    config.gemm_opt = False
    config.chunk_size = "none"

    os.environ["VLLM_TRITON_DECODE_KERNEL"] = config.triton_decode_kernel

    # Disable forced per-beam lengths so the engine generates naturally and we
    # capture the resulting token counts as the trace.
    best_of_n_beam_module.REQUEST_GEN_TOKENS = {}

    num_gpus = torch.cuda.device_count()
    llm = LLM(
        model=config.model_path,
        gpu_memory_utilization=config.gpu_memory_utilization,
        enable_prefix_caching=True,
        seed=config.seed,
        tensor_parallel_size=num_gpus,
        load_format="safetensors",
        task="generate",
        dtype="auto",
        disable_cascade_attn=True,
    )
    if config.disable_prm:
        logger.info("PRM disabled via config.disable_prm — placeholder pred from beam 0.")
        prm = None
    else:
        prm = load_prm(config)

    logger.info("Warming up FA and FD-path Triton kernels...")
    _warmup_attn_kernels(llm)
    logger.info("Warmup done.")

    dataset = get_dataset(config)
    dataset = dataset.map(
        best_of_n_beam,
        batched=True,
        batch_size=config.search_batch_size,
        with_indices=True,
        fn_kwargs={"config": config, "llm": llm, "prm": prm},
        desc="Tracing best-of-n",
        load_from_cache_file=False,
    )

    dataset = score(dataset, config)
    save_dataset(dataset, config)

    trace = {}
    timings = {}
    for problem_idx, example in enumerate(dataset):
        for beam_idx, token_length in enumerate(example.get("completion_tokens", [])):
            trace[(problem_idx, beam_idx)] = int(token_length)
        for beam_idx, gen_time_ms in enumerate(example.get("request_timings", [])):
            timings[(problem_idx, beam_idx)] = float(gen_time_ms)

    output_dir = config.output_dir or f"data/{config.model_path}"
    dataset_short_name = config.dataset_name.split("/")[-1]
    trace_path = Path(output_dir) / dataset_short_name / f"beams={config.n}"
    _write_trace(trace, trace_path)
    csv_path = trace_path.with_suffix(".csv")
    _write_trace_csv(trace, csv_path)
    timing_csv_path = trace_path.parent / f"beams={config.n}_timing.csv"
    _write_timing_csv(timings, timing_csv_path)
    logger.info(
        "Saved %d trace entries to %s, %s and %s",
        len(trace),
        trace_path,
        csv_path,
        timing_csv_path,
    )


if __name__ == "__main__":
    main()
